apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iuxuser
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        run: iuxuser
    spec:
      containers:
      - name: iuxuser
        image: 
        ports:
        - containerPort: 8080
        
---



apiVersion: v1
kind: Service
metadata:
  name: iuxuser
  labels:
    run: iuxuser
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    run: iuxuser


